version: "3.9"

services:
  backend:
    build:
      context: ./api-node/backend
      dockerfile: Dockerfile
    container_name: issue-tracker-backend
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CLASSIFIER_URL=http://classifier:8001/classify
    ports:
      - "3000:3000"
    depends_on:
      - classifier

  classifier:
    build:
      context: ./api-node/classifier
      dockerfile: Dockerfile
    container_name: issue-tracker-classifier
    environment:
      - PORT=8001
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - ./api-node/classifier:/app

  frontend:
    build:
      context: ./api-node/frontend
      dockerfile: Dockerfile
    container_name: issue-tracker-frontend
    environment:
      # El frontend consumir√° al backend usando el nombre del servicio de docker
      - VITE_API_URL=http://backend:3000/api
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - backend

volumes:
  sqlite_data:
